### ISSUE TITLE
spatial attention module sigmoid

### ISSUE THREAD

**Issue by jimmyl02** [Peachypie98/CBAM#2]
Thanks for open sourcing your implementation, the code is really clean and easy to read.

Quick question with your SAM (spatial attention module) implementation, in the paper it looks like there is a sigmoid applied before multiplying with the feature. Looks like you have this for the channel attention module as well.

Is it just a missed part of the implementation? i.e should https://github.com/Peachypie98/CBAM/blob/main/cbam.py#L16 instead be `output = F.sigmoid(output) * x`

**Comment by Peachypie98** [comment]
Thank you for identifying the issue. You're right, I overlooked the implementation of the sigmoid function in the SAM. I'll make the corrections to the code as soon as possible. However, if you prefer, you are welcome to adjust the code on your own.
